--[[
	Enchantrix Addon for World of Warcraft(tm).
	Version: <%version%> (<%codename%>)
	Revision: $Id: EnxConstants.lua 4632 2010-01-24 02:33:54Z ccox $
	URL: http://enchantrix.org/

	Enchantrix Constants for Jewelcrafting / Prospecting

	License:
		This program is free software; you can redistribute it and/or
		modify it under the terms of the GNU General Public License
		as published by the Free Software Foundation; either version 2
		of the License, or (at your option) any later version.

		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.

		You should have received a copy of the GNU General Public License
		along with this program(see GPL.txt); if not, write to the Free Software
		Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

	Note:
		This AddOn's source code is specifically designed to work with
		World of Warcraft's interpreted AddOn system.
		You have an implicit license to use this AddOn with these facilities
		since that is its designated purpose as per:
		http://www.fsf.org/licensing/licenses/gpl-faq.html#InterpreterIncompat
]]
Enchantrix_RegisterRevision("$URL: http://dev.norganna.org/auctioneer/trunk/Enchantrix/EnxConstantsJewelcrafting.lua $", "$Rev: 4632 $")

local const = Enchantrix.Constants

-- Dragonflight (DF) Ores-n-Gems
local SEREVITEI                = 190395
local SEREVITEII               = 190396
local SEREVITEIII              = 190394
local DRACONIUMI               = 189143
local DRACONIUMII              = 188658
local DRACONIUMIII             = 190311
local KHAZGORITEI              = 190312
local KHAZGORITEII             = 190313
local KHAZGORITEIII            = 190314
local PRISMATIC                = 194545
local GEM_ALEXSTRASZITEI       = 192852
local GEM_ALEXSTRASZITEII      = 192853
local GEM_ALEXSTRASZITEIII     = 192855
local GEM_ILLIMITED_DIAMONDI   = 192869 -- left off of prospecting as i think it's soley created from alchemy, but not postive
local GEM_ILLIMITED_DIAMONDII  = 192870 -- left off of prospecting as i think it's soley created from alchemy, but not postive
local GEM_ILLIMITED_DIAMONDIII = 192871 -- left off of prospecting as i think it's soley created from alchemy, but not postive
local GEM_MALYGITEI            = 192856
local GEM_MALYGITEII           = 192857
local GEM_MALYGITEIII          = 192858
local GEM_NELTHARITEI          = 192862
local GEM_NELTHARITEII         = 192863
local GEM_NELTHARITEIII        = 192865
local GEM_NOZDORITEI           = 192866
local GEM_NOZDORITEII          = 192867
local GEM_NOZDORITEIII         = 192868
local GEM_YSEMERALDI           = 192859
local GEM_YSEMERALDII          = 192860
local GEM_YSEMERALDIII         = 192861

-- The War Within (TWW) Ores-n-Gems
local NULL_STONE                = 210939
local IMPERFECT_NULL_STONE      = 217707  -- left off prospecting because i havent seen it in there. may not have had enough.
local BISMUTHI                  = 210930
local BISMUTHII                 = 210931
local BISMUTHIII                = 210932
local IRONCLAWI                 = 210936
local IRONCLAWII                = 210937
local IRONCLAWIII               = 210938
local AQUIRITEI                 = 210933
local AQUIRITEII                = 210934
local AQUIRITEIII               = 210935
local GEM_AMBIVALENT_AMBER      = 212498
local GEM_BLASPHEMITE           = 212514 -- left off of prospecting as i think it's soley created from alchemy, but not postive
local GEM_EXTRAVAGANT_EMERALD   = 212505
local GEM_OSTENTATIOUS_ONYX     = 212511
local GEM_RADIANT_RUBY          = 212495
local GEM_STUNNING_SAPPHIRE     = 212508
local HANDFUL_OF_PEBBLES        = 213398
local GLITTERING_GLASS          = 213399
local CRUSHED_GEMSTONES         = 213219

--[[
	Prospectable ores and skill to prospect them.
	Not sure if Classic would be needed prior to DF bcoming covered by Classic.
	Classic removed for splification as it would be covered through previous file adjustment at this time.

	Aside form Min Levels; Data needs to be gathered from WoWHead, WoWWiki, Etc and updated
		Current #s are Guesses
]]
if not const.Classic then
	const.ProspectDFPMinLevels = {
		[SEREVITEI] = 1,
		[SEREVITEII] = 1,
		[SEREVITEIII] = 1,
		[DRACONIUMI] = 1,
		[DRACONIUMII] = 1,
		[DRACONIUMIII] = 1,
		[KHAZGORITEI] = 1,
		[KHAZGORITEII] = 1,
		[KHAZGORITEIII] = 1,
		[PRISMATIC] = 1,
		[NULL_STONE] = 1,
		[BISMUTHI] = 1,
		[BISMUTHII] = 1,
		[BISMUTHIII] = 1,
		[IRONCLAWI] = 1,
		[IRONCLAWII] = 1,
		[IRONCLAWIII] = 1,
		[AQUIRITEI] = 1,
		[AQUIRITEII] = 1,
		[AQUIRITEIII] = 1,
		[HANDFUL_OF_PEBBLES] = 1,
	}
end

const.DFPProspectableItems = {
	-- DF Ores to Gems
	[SEREVITEI] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[SEREVITEII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[SEREVITEIII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[DRACONIUMI] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[DRACONIUMII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[DRACONIUMIII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[KHAZGORITEI] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[KHAZGORITEII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[KHAZGORITEIII] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
	},
	[PRISMATIC] = {
		[GEM_ALEXSTRASZITEI] = 0.75,
		--[GEM_ALEXSTRASZITEII] = 0.5,
		--[GEM_ALEXSTRASZITEIII] = 0.25,
		[GEM_MALYGITEI] = 0.75,
		--[GEM_MALYGITEII] = 0.5,
		--[GEM_MALYGITEIII] = 0.25,
		[GEM_NELTHARITEI] = 0.75,
		--[GEM_NELTHARITEII] = 0.5,
		--[GEM_NELTHARITEIII] = 0.25,
		[GEM_NOZDORITEI] = 0.75,
		--[GEM_NOZDORITEII] = 0.5,
		--[GEM_NOZDORITEIII] = 0.25,
		[GEM_YSEMERALDI] = 0.75,
		--[GEM_YSEMERALDII] = 0.5,
		--[GEM_YSEMERALDIII] = 0.25,
		[KHAZGORITEI] = .1
	},

	-- TWW Ores to Gems
	[NULL_STONE] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[BISMUTHI] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[BISMUTHII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[BISMUTHIII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[IRONCLAWI] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[IRONCLAWII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[IRONCLAWIII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[AQUIRITEI] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[AQUIRITEII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[AQUIRITEIII] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[HANDFUL_OF_PEBBLES] = 0.75,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
	[HANDFUL_OF_PEBBLES] = {
		[GEM_AMBIVALENT_AMBER] = 0.25,
		[GEM_EXTRAVAGANT_EMERALD] = 0.25,
		[GEM_OSTENTATIOUS_ONYX] = 0.25,
		[GEM_RADIANT_RUBY] = 0.25,
		[GEM_STUNNING_SAPPHIRE] = 0.25,
		[GLITTERING_GLASS] = 0.75,
		[CRUSHED_GEMSTONES] = 0.25,
	},
}

const.DFPReverseProspectingSources = {
	-- DF Section
	[GEM_ALEXSTRASZITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_ALEXSTRASZITEII] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_ALEXSTRASZITEIII] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_MALYGITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_MALYGITEII] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_MALYGITEIII] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NELTHARITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NELTHARITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NELTHARITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NOZDORITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NOZDORITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_NOZDORITEI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_YSEMERALDI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_YSEMERALDI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 
	[GEM_YSEMERALDI] = { SEREVITEI, SEREVITEII, SEREVITEIII, DRACONIUMI, DRACONIUMII, DRACONIUMIII, KHAZGORITEI, KHAZGORITEII, KHAZGORITEIII, PRISMATIC }, 

	-- TWW Section
	[GEM_AMBIVALENT_AMBER] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[GEM_EXTRAVAGANT_EMERALD] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[GEM_OSTENTATIOUS_ONYX] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[GEM_RADIANT_RUBY] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[GEM_STUNNING_SAPPHIRE] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[HANDFUL_OF_PEBBLES] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII },
	[GLITTERING_GLASS] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
	[CRUSHED_GEMSTONES] = { NULL_STONE, BISMUTHI, BISMUTHII, BISMUTHIII, IRONCLAWI, IRONCLAWII, IRONCLAWIII, AQUIRITEI, AQUIRITEII, AQUIRITEIII, HANDFUL_OF_PEBBLES },
}

